POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "New person",
  "number": "12343424-12348289"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "12343424-12348289"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "12343424-12348289"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Valid name",
  "number": ""
}
